#!/bin/sh

# Adapted from https://github.com/cknadler/vim-anywhere

TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")

mkdir -p $TMPFILE_DIR
touch $TMPFILE

chmod o-r $TMPFILE # Make file only readable by you
kitty -e nvim $TMPFILE
cat $TMPFILE | wl-copy
